### ISSUE TITLE
Use svgo to compress existing svg assets

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1368]
```
npm install svgo --save-dev
```

Add an .svgo.yml
```
plugins:

  - removeXMLProcInst: false
  - collapseGroups: false
  - mergePaths: false
  - cleanupIDs: false
  - convertPathData: false
  - removeDesc: false
  - removeTitle: false
  - removeViewBox: false
```

and add a svg minification job to package.json

```
"svg-min": "svgo static/images/**/*.svg && svgo static/images/*.svg",
```

Finally, run it and commit all the compressed SVGs for a performance win!
