### ISSUE TITLE
Run flake8 checks in Travis on modified code

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2300]
### Is your feature request related to a problem? Please describe.
We can currently introduce flake8 errors into our code and have no linting/error checking.

### Describe the solution you'd like
This site shows how to run flake8 tests on the modified code. It's in the context of pre-commit hooks, but could we use the code in our Travis build? 
- https://consideratecode.com/2016/10/15/check-code-changes-with-flake8-before-committing/

Code from site:
```sh
git diff --cached -U0 | flake8 --diff
```

It notes that this won't catch _all_ issues, so another check that could be performed would be to perform a full check on master and on the PR, and ensure the outputs are the same (i.e. no new errors).

### Stakeholders
@cclauss @hornc

**Comment by cclauss** [comment]
$ make lint  # Travis CI runs this on every code change and it can be run locally by contributors.
https://github.com/internetarchive/openlibrary/blob/master/Makefile#L95

**Comment by cclauss** [comment]
If you are really determined then locally you can also set a precommit-hook that won't even allow your commits to complete until some automated tests pass.  You create a __.pre-commit-config.yaml__ file at the root of the project.

This would be overkill for this project but for one of my projects, the __.pre-commit-config.yaml__ file looks like this:
```yaml
language_version: python3.7
repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.7'  # pick a git hash / tag to point to
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.701'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        # By default, mypy will run with mypy --ignore-missing-imports,
        # pre-commit runs mypy from an isolated virtualenv so it won't
        # have access to those. To change the arguments, override the
        # args as follows:
        # args: [--no-strict-optional, --ignore-missing-imports]
```
