### ISSUE TITLE
Adding two new identifiers

### ISSUE THREAD

**Issue by FinixFighter** [internetarchive/openlibrary#5275]
Hi! I found two databases which are very useful and contain a lot of information about comic books. These two are the Grand Comics Database https://www.comics.org/ and I.N.D.U.C.K.S https://inducks.org/. 

I think it would be good to add them to the list of identifiers, so that we can also add the respective ID numbers other than ISBN, Google, Amazon, etc... 
These two database (INDUCKS in particular) contain tons of information about comic books, so that if someone wants more information about that book, he/she can easily see it just by one click.

Once we can add GCD and INDUCKS identifiers, we might even think about creating a bot for adding/updating books from those sources.

**Comment by RayBB** [comment]
For anyone looking to do this you'll probably have to edit the config as mentioned here https://github.com/internetarchive/openlibrary/pull/5093#issuecomment-832196948

**Comment by cdrini** [comment]
Sounds good! Easy to add; I need information in this format. Is there a pattern to the URLs? That way we can correctly link to them in the UI :)

```yaml

    label: W. W. Norton
    name: w._w._norton
    notes:
    url: http://books.wwnorton.com/books/detail.aspx?ID=@@@
    website: http://wwnorton.com

```
