### ISSUE TITLE
Add a hover effect to the donate button

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5756]
As @cdrini mentioned in https://github.com/internetarchive/openlibrary/pull/5708#issuecomment-935040084 it would be fun to have a hover effect for the donate button. 

Could be a good first issue for someone.

### Describe the problem that you'd like solved
A hover effect for the donate button to add some charm to the website.

### Proposal & Constraints
I don't know what exactly drini had in mind so I'll encourage people to be creative with suggestions.

It is a very subjective ask so please do share your thoughts (hopefully with a little example) but be aware we can't accept every suggestion so please don't take it personally if yours isn't selected.

### Additional context
Change should happen in this file:
https://github.com/internetarchive/openlibrary/blob/master/static/css/components/buttonGhost.less

### Stakeholders

@cdrini

**Comment by ma8642** [comment]
I'd like to try having the button do a heartbeat animation on hover!  Will create a PR when it's ready.

**Comment by shashwat73** [comment]
Changed the text to red. I can work on an animation, like a fade or something if you'd like. I thought it'd be a little too much.

https://github.com/internetarchive/openlibrary/compare/master...shashwat73:patch-1

**Comment by cdrini** [comment]
Definitely looking for something a bit more playful/creative! Here's one possibility for inspiration:

![heart donate](https://user-images.githubusercontent.com/6251786/141500459-17a66934-2837-4712-a5ce-52d227c9d609.gif)

```css
.iaBar a:last-child {
   margin-left:auto;
   overflow: clip;
  transition: padding .3s;
}

.iaBar a:last-child .heart {
  font-size: 1.6em;
  line-height: 0;
  font-family: system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji;
  transition: transform .3s, color .3s, margin-right .3s;
  display: inline-block;

  vertical-align: sub;
  width: 16x;
}

.iaBar a:last-child:hover {
  border-color: #700;
  padding-left: 16px;
  padding-right: 16px;
}

.iaBar a:last-child:hover .heart {
  transform: scale(20);
  color: #D55;
  mix-blend-mode: lighten;
  margin-right: -16px;
}
```
