### ISSUE TITLE
Add IDs and classification

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6590]
@cdrini 

### ✅ Бібліотечно-бібліографічна класифікація (Ukrainian)|  Library-Bibliographical Classification (English, not sure if it's correct translation because there is no Wikipedia article)
This classification was created in the 1960s in the USSR. It is an official classification system in russia and had been official on par with Universal Decimal Classification in Ukraine by 2017
https://uk.wikipedia.org/wiki/%D0%91%D1%96%D0%B1%D0%BB%D1%96%D0%BE%D1%82%D0%B5%D1%87%D0%BD%D0%BE-%D0%B1%D1%96%D0%B1%D0%BB%D1%96%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D1%96%D1%87%D0%BD%D0%B0_%D0%BA%D0%BB%D0%B0%D1%81%D0%B8%D1%84%D1%96%D0%BA%D0%B0%D1%86%D1%96%D1%8F

```
-   label: Library-Bibliographical Classification

    name: library_bibliographical_classification
```
### ✅ Фоліо | Folio
https://folio.com.ua/books/Istoriya-UPA
https://folio.com.ua/books/Zolota-osin-getmanshchini
https://folio.com.ua/books/Pohodi-Bogdana-Hmelnickogo
"Фоліо" (Folio) is one of the biggest Ukrainian publishers. In case of this site, the ID is text after: books/ 
This ID applies to the edition
```
-   label: Фоліо
    name: folio
    notes: 
    url: https://folio.com.ua/books/@@@
```

### ⬜ MyAnimeList
This site is focused on manga and light novels. They only have work-level ID 

```
-   label: MyAnimeList
    name: myanimelist
    notes: 
    url: https://myanimelist.net/manga/@@@
```
