### ISSUE TITLE
Dev instance requires librarians usergroup

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#693]
The dev instance errors because it expects the usergroup `/usergroup/librarians` after #664 .

Here is the error that appears on the homepage: http://bl.ocks.org/cdrini/raw/b93f021e83065ddaf1b9b0f83dafcf83/

**Comment by cdrini** [comment]
I think this could be fixed by updating the dev-instance database.

It looks like that happens here: https://github.com/internetarchive/openlibrary/blob/d3ccbd8e88210764612df403db0ff301aa98059b/scripts/bootstrap.sh#L69-L71

I think we can add the usergroup if we:

1) create a new dev environment
2) create the usergroup
3) export the psql database into a pg_dump file
4) update the dump file

**Comment by cdrini** [comment]
Work around: 

Change this:
```yml
    merge-authors:
        filter: usergroup
        usergroup: /usergroup/librarians
```

to this:
```yml
    merge-authors: admin
```
