### ISSUE TITLE
Add PYTHONUNBUFFERED=1 to docker-compose.override.yml

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#7186]
Python is (I think) buffering output inside the Docker containers, such that if there is an error, and one is engaging in the very bad habit of using `print` to gain insight, that `print()` output may not appear at all, or may show up after the error at some indeterminate point once the buffer fills further.

See this Stack Overflow question: https://stackoverflow.com/questions/59812009/what-is-the-use-of-pythonunbuffered-in-docker-file

### Describe the problem that you'd like solved

I'd like the docker-compose config to changed to export the `PYTHONUNBUFFERED` environment variable. 

Or in the alternative, this could be exported in the Dockerfiles themselves, though that would require rebuilding the containers, whereas changing the docker-compose configuration would not.

### Proposal & Constraints

Edit `docker-compose.override.yml` to add `PYTHONUNBUFFERED=1` to the environment:

```yml
version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.oldev
    [...]
    environment:
      - PYTHONUNBUFFERED=1
```

I'll submit a PR for this just in case I'm not the only one editing their docker-compose to add this.
