### ISSUE TITLE
Add trending score to solr

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7429]
We would love to be able to see trending items in a given collection (eg what's trending today in `subject:fantasy` ?). This would be a useful sorting parameter for many pages (eg Library Explorer, subject pages, trending carousel), that would provide interesting books while also providing a good variety of books.

In order to do this we need a score to be stored in solr. We can do this using a z score algorithm like the [one described here](https://stackoverflow.com/questions/787496/what-is-the-best-way-to-compute-trending-topics-or-tags).

We'd need a few new solr fields:

```yml
# The last 24 hours of trending actions
trending_actions_hourly: [0,0,0,0,1,1,0, ...] # len: 24
# The last 30 days of trending actions as a json blob
trending_actions_daily: [0,1,4,3,2,0,0,12, ...] # len: 30
# The trending zscore as a number
trending_score: 0.645
```

Then the rough formula is:

```py
trending_score = (views_today - average_views_per_day) / standard_dev_of_views_per_day
```

We would then need:

- a script that every day updates all `trending_actions_daily` and `trending_score`
- a script that every hour updates `trending_actions_hourly` and `trending_score`
- whenever a trending action occurs (eg a want to read, etc), update `trending_actions_hourly` and `trending_actions_monthly` and `trending_score`
- Use [solr partial document updates](https://solr.apache.org/guide/8_11/updating-parts-of-documents.html) for everything to make performant
