### ISSUE TITLE
Prototype 2 series data model approaches and pick one

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7588]
Subtask of #6718

**Comment by cdrini** [comment]
Implemented [Model Approach 1: Series as lists](https://docs.google.com/document/d/1kMGlBHIRONt0YOG2ffhjQpJjf_ABDZ2RBSFoW9xEkUU/edit#heading=h.vhk00gvms9pn) only, this seemed to work quite well, so moving forward with it for now.

The data model will be something like:

```yml
key: /lists/OL42L
type: { key: /type/list }
list_type: series
name: "Harry Potter"
description: "..."
seeds:
- { position: 1, item: { key: OL1W }, primary: true }
- { position: 2, item: { key: OL2W }, primary: true }
- { position: 0, item: { key: OL1513W }, primary: false }
- { position: 8, item: { key: OL1513W }, primary: false }
- { position: ‘1-7’, item: { key: OL12W }, compendium: true }
```

Note that this extends lists to have _annotated_ seeds, as opposed to pure seeds.

Here are some screenshots from the demo:

A series page:
![image](https://user-images.githubusercontent.com/6251786/233438834-95726713-4b65-49d5-9b0c-1a4dfdc2076a.png)

Editing a series page:
![image](https://user-images.githubusercontent.com/6251786/233438986-998287e2-c9d9-43e3-a221-d40233e7a8da.png)

Creating a new global series:
![image](https://user-images.githubusercontent.com/6251786/233439132-697ec615-3f72-4fdd-a817-4bc680b6a3ce.png)


Here is the proof of concept PR: https://github.com/internetarchive/openlibrary/pull/7804
