### ISSUE TITLE
Universal Authority File (GND) id for authors

### ISSUE THREAD

**Issue by bitnapper** [internetarchive/openlibrary#8037]
The German National Library has an authority file for personal names, subject headings and corporate bodies. Those are supported for editions but not for authors.

### Describe the problem that you'd like solved
Add support for GND in author pages.

Example link: https://d-nb.info/gnd/115406344
RegEx for the ID: (|1[012]?\d{7}[0-9X]|[47]\d{6}-\d|[1-9]\d{0,7}-[0-9X]|3\d{7}[0-9X])

**Comment by cdrini** [comment]
I'm going to need some help on this one, could you put them in a format like this:

```yaml
-   label: BookBrainz
    name: bookbrainz
    url: https://bookbrainz.org/author/@@@
    website: https://bookbrainz.org
```

I'm not to sure what the label should be. Also for the name, should we use `gnd` ? Or `dnb`? We already have an edition identifier that's sort of similar to this:

```yaml
-   label: Deutsche National Bibliothek
    name: dnb
    notes: ''
    url: http://d-nb.info/@@@
    website: http://www.d-nb.de/eng/index.htm
```

Are these the same identifier? Can we use the same `name` / url?

**Comment by bitnapper** [comment]
> I'm not to sure what the label should be. Also for the name, should we use `gnd` ? Or `dnb`? We already have an edition identifier that's sort of similar to this:

GND would be right. It refers to the id, DNB is the abbreviation for the German National Library.

```yaml
-   label: Deutsche National Bibliothek
    name: GND
    notes: ''
    url: 	https://d-nb.info/gnd/@@@
    website: http://www.d-nb.de/
```

> Are these the same identifier? Can we use the same `name` / url?
