### ISSUE TITLE
Add MusicBrainz identifiers for Authors, Works, Editions

### ISSUE THREAD

**Issue by Freso** [internetarchive/openlibrary#8897]
### Describe the problem that you'd like solved

More identifiers is more better, and currently the only way to link OL items to MBIDs is to use hyperlinks rather than specifying IDs together with other IDs. While obviously not everything in MusicBrainz will (or should be) represented in Open Library, there is a significant amount of audiobooks that are catalogued in both places. There are also several OL Authors who also happen to do music or other work that warrants a MusicBrainz entry for them, as well as musicians who also happen to be authors.

### Proposal & Constraints

Allow [MusicBrainz identifiers/IDs (MBIDs)](https://musicbrainz.org/doc/MusicBrainz_Identifier) for

- [ ] Authors ([MB Artists](https://musicbrainz.org/doc/Artist))
- [ ] Works ([MB Works](https://musicbrainz.org/doc/Work)) [depends on <https://github.com/internetarchive/openlibrary/issues/3430>]
- [ ] Editions ([MB Releases](https://musicbrainz.org/doc/Release))

### Additional context

Proposed YAML to be included:
* `author.yml`:
  ```yaml
  -   label: MusicBrainz
      name: musicbrainz
      url: https://musicbrainz.org/artist/@@@
      website: https://musicbrainz.org
  ```
* `work.yml`:
  ```yaml
  -   label: MusicBrainz
      name: musicbrainz
      url: https://musicbrainz.org/work/@@@
      website: https://musicbrainz.org
  ```
* `edition.yml`:
  ```yaml
  -   label: MusicBrainz
      name: musicbrainz
      url: https://musicbrainz.org/release/@@@
      website: https://musicbrainz.org
  ```
