### ISSUE TITLE
Add BookBrainz identifiers for Authors, Works, Editions

### ISSUE THREAD

**Issue by Freso** [internetarchive/openlibrary#8898]
Note: This is to some degree a duplicate of <https://github.com/internetarchive/openlibrary/issues/8480>, but more narrowly focusing on BookBrainz.

### Describe the problem that you'd like solved

More identifiers is more better, and currently the only way to link OL items to BBIDs is to use hyperlinks rather than specifying IDs together with other IDs. BookBrainz hopes to encompass everything in Open Library but also casts a much wider net for what it considers literature that is thus applicable to be entered into BB.

### Proposal & Constraints
Add BookBrainz identifiers/IDs (BBIDs) (UUIDs similar to [MusicBrainz IDs](https://musicbrainz.org/doc/MusicBrainz_Identifier)) for:

- [ ] Authors ([BB Authors](https://bookbrainz-dev-docs.readthedocs.io/en/latest/docs/schema.html#entities-description))
- [ ] Works ([BB Works](https://bookbrainz-user-guide.readthedocs.io/en/latest/style/entities/work/)) [depends on <https://github.com/internetarchive/openlibrary/issues/3430>]
- [ ] Editions ([BB Editions](https://bookbrainz-user-guide.readthedocs.io/en/latest/style/entities/edition/))

### Additional context

Proposed YAML to be included:
* `author.yml`:
  ```yaml
  -   label: BookBrainz
      name: bookbrainz
      url: https://bookbrainz.org/author/@@@
      website: https://bookbrainz.org
  ```
* `work.yml`:
  ```yaml
  -   label: BookBrainz
      name: bookbrainz
      url: https://bookbrainz.org/work/@@@
      website: https://bookbrainz.org
  ```
* `edition.yml`:
  ```yaml
  -   label: BookBrainz
      name: bookbrainz
      url: https://bookbrainz.org/edition/@@@
      website: https://bookbrainz.org
  ```
